/** @type {import('next').NextConfig} */

const cspHeader = `
    default-src 'self';
    script-src 'self' 'unsafe-eval' 'unsafe-inline' *.vercel-scripts.com *.vercel-insights.com;
    style-src 'self' 'unsafe-inline';
    img-src 'self' blob: data: *.graphassets.com;
    font-src 'self';
    object-src 'none';
    base-uri 'self';
    form-action 'self';
    frame-ancestors 'none';
    upgrade-insecure-requests;
`;

/* The CV PDF is generated by engaging-service and stored in R2, rather than
   built here. The bucket's public URL is rate-limited by Cloudflare and not
   meant to be user-facing, and a custom domain would need this domain's DNS
   moved off Vercel — so it is proxied instead. Visitors see our own path,
   and Vercel's CDN absorbs the traffic so R2 is rarely hit.

   Not a secret: this is a public bucket URL. It lives here rather than in an
   env var so the config is self-contained and cannot half-work. */
const artifacts = 'https://pub-53c526b0d6a84a57afc0b459064235fd.r2.dev';

const nextConfig = {
  /* The OG route reads this at runtime with fs, which the bundler cannot see,
     so it has to be traced in explicitly. Without it the route throws only
     once deployed. */
  outputFileTracingIncludes: {
    '/api/og': ['./src/assets/fonts/**'],
  },
  /* beforeFiles, so the proxy wins over anything left in public/. */
  rewrites: async () => ({
    beforeFiles: [
      {
        source: '/billy-watson-cv.pdf',
        destination: `${artifacts}/billy-watson-cv.pdf`,
      },
      /* The PWA splash screens, one per device profile per page. Their paths
         are unchanged, so getStartupImages still builds them the same way. */
      {
        source: '/startup-:name.png',
        destination: `${artifacts}/startup-:name.png`,
      },
    ],
    afterFiles: [],
    fallback: [],
  }),
  headers: async () => [
    {
      source: '/(.*)',
      headers: [
        {
          key: 'Content-Security-Policy',
          value: cspHeader.replace(/\n/g, ''),
        },
      ],
    },
  ],
  images: {
    /* Trimmed from the default tail of [..., 2048, 3840]. Every candidate
       here is spelled out in full in the srcset of any image that ships a
       `sizes` prop, and nothing on this site is ever laid out wider than
       448px, so the retina ceiling is comfortably under 1920. */
    deviceSizes: [640, 750, 828, 1080, 1200, 1920],
    imageSizes: [120, 144, 160, 200, 240, 280, 320, 360],
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'eu-west-2.graphassets.com',
      },
    ],
  },
};

export default nextConfig;
